name: ignition # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.0.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: Hit the ground running on your fresh Ubuntu installation. # 79 char long summary
description: |
  The Linux world is full of apps. You could be looking for an app that does something, only to find that there are literally hundreds of options. Ignition will show you common apps for certain categories and explain their little nuances in an easy format. Just choose the ones to install, and Ignition will start the engine.

  This app is still in `devel/alpha`. It isn't fully functional and should only be used for development and testing purposes.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  ignition:
    command: src/ignition
    desktop: ignition.desktop

parts:
  ignition:
    # See 'snapcraft plugins'
    plugin: python
    python-version: python3
    source: .
  

